name: pinboard
version: '0.1.3'
summary: Pinboard
description: | 
  Make virtual interactive pinboards easily
icon: src/ressources/icon.svg

grade: stable
confinement: strict
base: core18

apps:
  pinboard:
        command: python3 $SNAP/src/pinboard.py
        extensions: [gnome-3-28]
        plugs:
            - home
            - audio-playback
            
parts:
  source-dump:
    plugin: dump
    source: .
  pinboard:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
        - libslang2
        - libgpm2
        - libpulse0
        - libgstreamer1.0-0
        - python3-wxgtk4.0
        - python3-wxgtk-media4.0
        - libgstreamer-plugins-base1.0-0
